module polytools
    implicit none

    contains
        function linspace(A,B,N)
            implicit none
            double precision              :: A,B
            integer                       :: N
            integer                       :: i
            double precision,dimension(N) :: linspace
            linspace = (/ (i,i=0,N-1) /)
            linspace = linspace / (N-1.) * (B-A)+A
            return
        end function linspace

        function logspace(A,B,N)
            implicit none
            double precision              :: A,B
            integer                       :: N
            integer                       :: i
            double precision,dimension(N) :: logspace
            logspace = (/ (i,i=0,N-1) /)
            logspace = logspace / (N-1.) * (B-A)+A
            logspace = 10**logspace
            return
        end function logspace

        subroutine getNumModels(models)
        !============================================================================
        ! PROGRAM: getNumModels
        !
        ! DESCRIPTION: Reads the lookup table generated by makeTable and retrieves
        !       the value from the first line giving the number of entries in the
        !       table, the number of 'models.'
        !
        ! CALLING SEQUENCE:
        !
        !       CALL getNumModels(models)
        !
        ! WRITTEN: Mikhail Klassen                            (McMaster University)
        !          2 / July / 2010
        !
        ! EMAIL: mikhail.klassen@gmail.com
        !============================================================================
            implicit none
	        integer :: models,ios

            open(UNIT=100,FILE="modeldata_table.dat",ACTION="read",&
                & POSITION="REWIND",IOSTAT=ios)
            if (ios /=0) then
                print *,'Error occurred trying to open file modeldata_table.dat for writing'
                stop
            end if
            read(UNIT=100,FMT=*),models
            close (UNIT=100)
        end subroutine getNumModels

        subroutine get_btable_numrows(nrows)
        !============================================================================
        ! PROGRAM: get_btable_numrows(nrows)
        !
        ! DESCRIPTION: Reads the first line from the beta table to calculate the
        !     number of rows in the data table.
        !
        ! CALLING SEQUENCE:
        !
        !       CALL get_btable_numrows(nrows)
        !
        ! WRITTEN: Mikhail Klassen                            (McMaster University)
        !          15 / July / 2010
        !
        ! EMAIL: mikhail.klassen@gmail.com
        !============================================================================
		    implicit none
		    integer, intent(out) :: nrows
		    integer              :: models,nMs,ios
		! Open input file for reading ===============================================
		    open(UNIT=100,FILE="beta_table.dat",ACTION="read",&
		        & POSITION="REWIND",IOSTAT=ios)
		    if (ios /=0) then
		        print *,'Error occurred trying to open file beta_table.dat for writing'
		        stop
		    end if
		! Read first line of file ===================================================
		    read(UNIT=100,FMT=201),models,nMs
		    nrows = models*(nMs-2)
		    201 format (2X,I4,2X,I4)
		end subroutine get_btable_numrows

        subroutine get_model_table_cols(models,n,xi,zfin,Dn,Bn,massparam)
        !============================================================================
        ! PROGRAM: get_model_table_cols
        !
        ! DESCRIPTION: Reads the lookup table generated by makeTable and stores the
        !       values in a 2D array. It then extracts the columns requested by the
        !       calling program and returns them as vectors. The length of these
        !       vectors depends on the number of rows in the table.
        !
        !       This program is intended to be coupled to the routines spline and
        !       seval. After the calling program has extracted the columns of
        !       interest, values intermediate to two entries in the vector can be
        !       generated by interpolation using those routines.
        !
        ! CALLING SEQUENCE:
        !
        !       CALL getNumModels(models)
        !       CALL get_model_table_cols(models,n=n,Dn=Dn)
        !
        !       All arguments are optional arguments, except 'models'. The keywords must be specified
        !       in the form of keyword=argument. getNumModels must be run first so that arrays can be
        !       sized correctly.
        !
        !      This example returns two vectors n and Dn.
        !
        ! WRITTEN: Mikhail Klassen                             (McMaster University)
        !          11 / June / 2010
        !
        ! MODIFIED: Mikhail Klassen                            (McMaster University)
        !          20 / July / 2010
        !
        ! EMAIL: mikhail.klassen@gmail.com
        !============================================================================
        implicit none
        double precision,dimension(models),intent(out),OPTIONAL :: n,xi
        double precision,dimension(models),intent(out),OPTIONAL :: zfin
        double precision,dimension(models),intent(out),OPTIONAL :: Dn,Bn
        double precision,dimension(models),intent(out),OPTIONAL :: massparam
        integer,intent(in)                                      :: models
        integer                                                 :: i,ios
        double precision,allocatable,dimension(:,:)             :: MODELDATA
        character(LEN=91)                                       :: HEADERS

        ! OPEN INPUT FILE FOR READING ===============================================
        open(UNIT=100,FILE="modeldata_table.dat",ACTION="read",&
            & POSITION="REWIND",IOSTAT=ios)
        if (ios /=0) then
            print *,'Error occurred trying to open file modeldata_table.dat for writing'
            stop
        end if
        ! READ FILE =================================================================
        read(UNIT=100,FMT=*)!,models
        allocate(MODELDATA(models,6))
        read (UNIT=100,FMT=200),HEADERS
            i=1
        do
            read(UNIT=100,FMT=201,IOSTAT=ios),MODELDATA(i,:)
            if (ios<0) EXIT ! Check to see if end-of-file reached
            !       write(*,201),MODELDATA(i,:) !Debug: Print each line
            i=i+1
        end do
        ! CLOSE FILE ================================================================
        close (UNIT=100)

        ! SEPARATE INTO VECTORS =====================================================
        if (present(n)) then
            !allocate(n(models))
            n = MODELDATA(:,1)
        endif
        if (present(xi)) then
            !allocate(xi(models))
            xi = MODELDATA(:,2)
        endif
        if (present(zfin)) then
            !allocate(zfin(models))
            zfin = MODELDATA(:,3)
        endif
        if (present(Dn)) then
            !allocate(Dn(models))
            Dn = MODELDATA(:,4)
        endif
        if (present(Bn)) then
            !allocate(Bn(models))
            Bn = MODELDATA(:,5)
        endif
        if (present(massparam)) then
            !allocate(massparam(models))
            massparam = MODELDATA(:,6)
        endif

        deallocate(MODELDATA)

        ! FORMAT STATEMENTS =========================================================
        199 format (1X,A,2X,I10)
        200 format (2X,A,8X,A,8X,A,4X,A,3X,A,6X,A)
        201 format (1X,F12.9,3X,F12.9,3X,F12.9,3X,F12.9,3X,F13.9,3X,F12.9)

        end subroutine get_model_table_cols

        subroutine get_beta_table_mvec(mvec)
        !============================================================================
        ! PROGRAM: get_beta_table_cols
        !
        ! DESCRIPTION:
        !
        ! CALLING SEQUENCE:
        !
        ! WRITTEN: Mikhail Klassen                             (McMaster University)
        !          20 / July / 2010
        !
        ! EMAIL: mikhail.klassen@gmail.com
        !============================================================================
        implicit none
        double precision,allocatable,dimension(:),intent(out) :: mvec
        integer                                               :: nMs,models
        integer                                               :: i,ios
        double precision,dimension(3)                         :: beta_table_tmp

        ! OPEN INPUT FILE FOR READING ===============================================
        open(UNIT=100,FILE="beta_table.dat",ACTION="read",&
            & POSITION="REWIND",IOSTAT=ios)
        if (ios /=0) then
            print *,'Error occurred trying to open file beta_table.dat for reading'
            stop
        end if
        ! READ FILE =================================================================
        read(UNIT=100,FMT=*) models,nMs

        allocate(mvec(nMs-2))

        do i=1,nMs-2
            read(UNIT=100,FMT=205,IOSTAT=ios) beta_table_tmp(:)
            if (ios<0) EXIT ! Check to see if end-of-file reached
            mvec(i) = beta_table_tmp(1)
        end do
        ! CLOSE FILE ================================================================
        close (UNIT=100)

        ! FORMAT STATEMENTS =========================================================
        205 format (2X,f20.16,5X,f18.16,5X,f19.16)

        end subroutine get_beta_table_mvec

end module polytools
